BLACKLIST = 1
WHITELIST = 2

# CONSTANT LIKE THINGS
defaultDb = '/etc/pihole/gravity.db'
# SOURCES
B_FIREBOG_NOCROSS = 1
B_FIREBOG_TICKED = 2
B_FIREBOG_ALL = 3


W_ANUDEEP_WHITE = 1
W_ANUDEEP_REFERRAL = 2
W_ANUDEEP_OPTIONAL = 3

FILE = 100
PASTE = 101
